version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mongo:4.4.5-bionic
    restart: always
    env_file:
      - env_data.env
    volumes:
      - .mongo_data:/data/db
    ports:
      - 37017:27017
